//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorAPI.AuthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.AuthServiceSoap")]
    public interface AuthServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateEMPLID", ReplyAction="*")]
        MonitorAPI.AuthService.AuthenticateEMPLIDResponse AuthenticateEMPLID(MonitorAPI.AuthService.AuthenticateEMPLIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateEMPLID", ReplyAction="*")]
        System.Threading.Tasks.Task<MonitorAPI.AuthService.AuthenticateEMPLIDResponse> AuthenticateEMPLIDAsync(MonitorAPI.AuthService.AuthenticateEMPLIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateEMPLIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateEMPLID", Namespace="http://tempuri.org/", Order=0)]
        public MonitorAPI.AuthService.AuthenticateEMPLIDRequestBody Body;
        
        public AuthenticateEMPLIDRequest() {
        }
        
        public AuthenticateEMPLIDRequest(MonitorAPI.AuthService.AuthenticateEMPLIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateEMPLIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string applicationdescription;
        
        public AuthenticateEMPLIDRequestBody() {
        }
        
        public AuthenticateEMPLIDRequestBody(string username, string password, string applicationdescription) {
            this.username = username;
            this.password = password;
            this.applicationdescription = applicationdescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateEMPLIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateEMPLIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public MonitorAPI.AuthService.AuthenticateEMPLIDResponseBody Body;
        
        public AuthenticateEMPLIDResponse() {
        }
        
        public AuthenticateEMPLIDResponse(MonitorAPI.AuthService.AuthenticateEMPLIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateEMPLIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateEMPLIDResult;
        
        public AuthenticateEMPLIDResponseBody() {
        }
        
        public AuthenticateEMPLIDResponseBody(string AuthenticateEMPLIDResult) {
            this.AuthenticateEMPLIDResult = AuthenticateEMPLIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthServiceSoapChannel : MonitorAPI.AuthService.AuthServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceSoapClient : System.ServiceModel.ClientBase<MonitorAPI.AuthService.AuthServiceSoap>, MonitorAPI.AuthService.AuthServiceSoap {
        
        public AuthServiceSoapClient() {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MonitorAPI.AuthService.AuthenticateEMPLIDResponse MonitorAPI.AuthService.AuthServiceSoap.AuthenticateEMPLID(MonitorAPI.AuthService.AuthenticateEMPLIDRequest request) {
            return base.Channel.AuthenticateEMPLID(request);
        }
        
        public string AuthenticateEMPLID(string username, string password, string applicationdescription) {
            MonitorAPI.AuthService.AuthenticateEMPLIDRequest inValue = new MonitorAPI.AuthService.AuthenticateEMPLIDRequest();
            inValue.Body = new MonitorAPI.AuthService.AuthenticateEMPLIDRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.applicationdescription = applicationdescription;
            MonitorAPI.AuthService.AuthenticateEMPLIDResponse retVal = ((MonitorAPI.AuthService.AuthServiceSoap)(this)).AuthenticateEMPLID(inValue);
            return retVal.Body.AuthenticateEMPLIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MonitorAPI.AuthService.AuthenticateEMPLIDResponse> MonitorAPI.AuthService.AuthServiceSoap.AuthenticateEMPLIDAsync(MonitorAPI.AuthService.AuthenticateEMPLIDRequest request) {
            return base.Channel.AuthenticateEMPLIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<MonitorAPI.AuthService.AuthenticateEMPLIDResponse> AuthenticateEMPLIDAsync(string username, string password, string applicationdescription) {
            MonitorAPI.AuthService.AuthenticateEMPLIDRequest inValue = new MonitorAPI.AuthService.AuthenticateEMPLIDRequest();
            inValue.Body = new MonitorAPI.AuthService.AuthenticateEMPLIDRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.applicationdescription = applicationdescription;
            return ((MonitorAPI.AuthService.AuthServiceSoap)(this)).AuthenticateEMPLIDAsync(inValue);
        }
    }
}
